import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.scss";
import NavbarWidget from "@/layout/navbarWidget/NavbarWidget";
import MainContent from "@/layout/mainContent/MainContent";
import WeatherWidget from "@/layout/weatherWidget/WeatherWidget";
import {Layout} from "@/layout/Layout";

const inter = Inter({subsets: ["latin"]});

function Home() {
    return (
        <>
            <Head>
                <title>Weather Dashboard</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Layout>
                    <div className={styles.content}>
                        <NavbarWidget/>
                        <MainContent/>
                        <WeatherWidget/>
                    </div>
                </Layout>

            </main>
        </>
    );
}

export default Home;
